// <auto-generated />
using System;
using MMAC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MMAC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260708064508_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MMAC.Models.Address.District", b =>
                {
                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<string>("IdCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameMM")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SRId")
                        .HasColumnType("integer");

                    b.Property<string>("SystemUse")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.HasKey("DistrictId");

                    b.HasIndex("SRId");

                    b.ToTable("District");
                });

            modelBuilder.Entity("MMAC.Models.Address.StateRegion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("IdCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameMM")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SystemUse")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.HasKey("Id");

                    b.ToTable("StateRegion");
                });

            modelBuilder.Entity("MMAC.Models.Address.Township", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<string>("IdCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameMM")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SystemUse")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Township");
                });

            modelBuilder.Entity("MMAC.Models.Audits.AuditLogs", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Inputted")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LogIPAddr")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TravellerId")
                        .HasColumnType("uuid");

                    b.HasKey("LogId");

                    b.HasIndex("TravellerId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("MMAC.Models.Cores.ArrivalApplication", b =>
                {
                    b.Property<Guid>("AppNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Accommodation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AddressInMyanmar")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AppStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedUser")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<string>("DigitalDeclarations")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<string>("HealthDeclaration")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HealthRecordUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MobileNumberMM")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<int>("ModeOfTravelId")
                        .HasColumnType("integer");

                    b.Property<int>("PortOfArrivalId")
                        .HasColumnType("integer");

                    b.Property<string>("PreviousCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PurposeOfVisit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReferenceNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("StateRegionId")
                        .HasColumnType("integer");

                    b.Property<int>("TownshipId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TravellerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("date");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("AppNo");

                    b.HasIndex("ModeOfTravelId");

                    b.HasIndex("PortOfArrivalId");

                    b.HasIndex("TownshipId");

                    b.HasIndex("TravellerId");

                    b.ToTable("ArrivalApplication");
                });

            modelBuilder.Entity("MMAC.Models.Cores.Traveller", b =>
                {
                    b.Property<Guid>("TravellerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("FatherName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("IssuedCountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NRC")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("NationalityCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PassportNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PlaceOfBirthCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("PlaceOfResidenceCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("UID")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("date");

                    b.Property<string>("VisaNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TravellerId");

                    b.HasIndex("IssuedCountryCode");

                    b.HasIndex("NationalityCode");

                    b.HasIndex("PlaceOfBirthCode");

                    b.HasIndex("PlaceOfResidenceCode");

                    b.ToTable("Traveller");
                });

            modelBuilder.Entity("MMAC.Models.Master.Country", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("CountryISOAlpha3Code");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NameMM")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("date");

                    b.HasKey("CountryCode");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("MMAC.Models.Master.ModeOfTravel", b =>
                {
                    b.Property<int>("ModeOfTravelId")
                        .HasColumnType("integer");

                    b.Property<string>("ModeOfTravelName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ModeOfTravelId");

                    b.ToTable("ModeOfTravel");
                });

            modelBuilder.Entity("MMAC.Models.Master.PortOfArrival", b =>
                {
                    b.Property<int>("PortOfArrivalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PortOfArrivalId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<int>("ModeOfTravelId")
                        .HasColumnType("integer");

                    b.Property<string>("PortOfArrivalName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("date");

                    b.HasKey("PortOfArrivalId");

                    b.HasIndex("ModeOfTravelId");

                    b.ToTable("PortOfArrival");
                });

            modelBuilder.Entity("MMAC.Models.NRC.NRC_StateRegion+NRCStateRegion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("CodeMM")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedIPAddr")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CreatedUser")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IdCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("SystemUse")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedIPAddr")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("NRC_StateRegion");
                });

            modelBuilder.Entity("MMAC.Models.NRC.NRC_Township", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("CodeMM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedIPAddr")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CreatedUser")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IdCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("NRC_SRId")
                        .HasColumnType("integer");

                    b.Property<string>("SystemUse")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedIPAddr")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("NRC_SRId");

                    b.ToTable("NRC_Township");
                });

            modelBuilder.Entity("MMAC.Models.Address.District", b =>
                {
                    b.HasOne("MMAC.Models.Address.StateRegion", "StateRegion")
                        .WithMany("Districts")
                        .HasForeignKey("SRId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StateRegion");
                });

            modelBuilder.Entity("MMAC.Models.Address.Township", b =>
                {
                    b.HasOne("MMAC.Models.Address.District", "District")
                        .WithMany("Townships")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("MMAC.Models.Audits.AuditLogs", b =>
                {
                    b.HasOne("MMAC.Models.Cores.Traveller", "Traveller")
                        .WithMany("AuditLogs")
                        .HasForeignKey("TravellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Traveller");
                });

            modelBuilder.Entity("MMAC.Models.Cores.ArrivalApplication", b =>
                {
                    b.HasOne("MMAC.Models.Master.ModeOfTravel", "selectedModeOfTravel")
                        .WithMany("ArrivalApplication")
                        .HasForeignKey("ModeOfTravelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MMAC.Models.Master.PortOfArrival", "selectedPortOfArrival")
                        .WithMany("ArrivalApplications")
                        .HasForeignKey("PortOfArrivalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MMAC.Models.Address.Township", "Township")
                        .WithMany("ArrivalApplications")
                        .HasForeignKey("TownshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MMAC.Models.Cores.Traveller", "Traveller")
                        .WithMany("ArrivalApplications")
                        .HasForeignKey("TravellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Township");

                    b.Navigation("Traveller");

                    b.Navigation("selectedModeOfTravel");

                    b.Navigation("selectedPortOfArrival");
                });

            modelBuilder.Entity("MMAC.Models.Cores.Traveller", b =>
                {
                    b.HasOne("MMAC.Models.Master.Country", "IssuedCountry")
                        .WithMany()
                        .HasForeignKey("IssuedCountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MMAC.Models.Master.Country", "Nationality")
                        .WithMany("Travellers")
                        .HasForeignKey("NationalityCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MMAC.Models.Master.Country", "PlaceOfBirth")
                        .WithMany()
                        .HasForeignKey("PlaceOfBirthCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MMAC.Models.Master.Country", "PlaceOfResidence")
                        .WithMany()
                        .HasForeignKey("PlaceOfResidenceCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IssuedCountry");

                    b.Navigation("Nationality");

                    b.Navigation("PlaceOfBirth");

                    b.Navigation("PlaceOfResidence");
                });

            modelBuilder.Entity("MMAC.Models.Master.PortOfArrival", b =>
                {
                    b.HasOne("MMAC.Models.Master.ModeOfTravel", "ModeOfTravel")
                        .WithMany("PortOfArrival")
                        .HasForeignKey("ModeOfTravelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModeOfTravel");
                });

            modelBuilder.Entity("MMAC.Models.NRC.NRC_Township", b =>
                {
                    b.HasOne("MMAC.Models.NRC.NRC_StateRegion+NRCStateRegion", "StateRegion")
                        .WithMany("Townships")
                        .HasForeignKey("NRC_SRId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StateRegion");
                });

            modelBuilder.Entity("MMAC.Models.Address.District", b =>
                {
                    b.Navigation("Townships");
                });

            modelBuilder.Entity("MMAC.Models.Address.StateRegion", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("MMAC.Models.Address.Township", b =>
                {
                    b.Navigation("ArrivalApplications");
                });

            modelBuilder.Entity("MMAC.Models.Cores.Traveller", b =>
                {
                    b.Navigation("ArrivalApplications");

                    b.Navigation("AuditLogs");
                });

            modelBuilder.Entity("MMAC.Models.Master.Country", b =>
                {
                    b.Navigation("Travellers");
                });

            modelBuilder.Entity("MMAC.Models.Master.ModeOfTravel", b =>
                {
                    b.Navigation("ArrivalApplication");

                    b.Navigation("PortOfArrival");
                });

            modelBuilder.Entity("MMAC.Models.Master.PortOfArrival", b =>
                {
                    b.Navigation("ArrivalApplications");
                });

            modelBuilder.Entity("MMAC.Models.NRC.NRC_StateRegion+NRCStateRegion", b =>
                {
                    b.Navigation("Townships");
                });
#pragma warning restore 612, 618
        }
    }
}
