// <auto-generated />
using System;
using MMAC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MMAC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522145933_CreateAddressAndNRC")]
    partial class CreateAddressAndNRC
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MMAC.Models.Address.District", b =>
                {
                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<string>("IdCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameMM")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SRId")
                        .HasColumnType("integer");

                    b.Property<string>("SystemUse")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.HasKey("DistrictId");

                    b.HasIndex("SRId");

                    b.ToTable("District");
                });

            modelBuilder.Entity("MMAC.Models.Address.StateRegion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("IdCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameMM")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SystemUse")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.HasKey("Id");

                    b.ToTable("StateRegion");
                });

            modelBuilder.Entity("MMAC.Models.Address.Township", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<string>("IdCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameMM")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SystemUse")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Township");
                });

            modelBuilder.Entity("MMAC.Models.NRC.NRC_StateRegion+NRCStateRegion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("CodeMM")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedIPAddr")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CreatedUser")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IdCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("SystemUse")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedIPAddr")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("NRC_StateRegion");
                });

            modelBuilder.Entity("MMAC.Models.NRC.NRC_Township", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("CodeMM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedIPAddr")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CreatedUser")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IdCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("NRC_SRId")
                        .HasColumnType("integer");

                    b.Property<string>("SystemUse")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedIPAddr")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UpdatedUser")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("NRC_SRId");

                    b.ToTable("NRC_Township");
                });

            modelBuilder.Entity("MMAC.Models.Address.District", b =>
                {
                    b.HasOne("MMAC.Models.Address.StateRegion", "StateRegion")
                        .WithMany("Districts")
                        .HasForeignKey("SRId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StateRegion");
                });

            modelBuilder.Entity("MMAC.Models.Address.Township", b =>
                {
                    b.HasOne("MMAC.Models.Address.District", "District")
                        .WithMany("Townships")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("MMAC.Models.NRC.NRC_Township", b =>
                {
                    b.HasOne("MMAC.Models.NRC.NRC_StateRegion+NRCStateRegion", "StateRegion")
                        .WithMany("Townships")
                        .HasForeignKey("NRC_SRId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StateRegion");
                });

            modelBuilder.Entity("MMAC.Models.Address.District", b =>
                {
                    b.Navigation("Townships");
                });

            modelBuilder.Entity("MMAC.Models.Address.StateRegion", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("MMAC.Models.NRC.NRC_StateRegion+NRCStateRegion", b =>
                {
                    b.Navigation("Townships");
                });
#pragma warning restore 612, 618
        }
    }
}
